### ISSUE TITLE
gulp-mocha

### ISSUE THREAD

**Issue by sindresorhus** [dylanb/gulp-blanket-mocha#1] opened 2014-01-08 23:47 UTC
I don't like how this is does multiple things. Maybe it could be combined with [gulp-mocha](https://github.com/sindresorhus/gulp-mocha) so you could do this:

``` js
var gulp = require('gulp');
var mocha = require('gulp-mocha');

gulp.task('default', function () {
    gulp.src('app.js')
        .pipe(mocha())
        .pipe(blanket());
});
```

// @contra

**Comment by yocontra** [comment] 2014-01-08 23:51
I agree there doesn't need to be two mocha plugins.

**Comment by dylanb** [comment] 2014-01-10 00:04
ok, so I made it so it can now combine with gulp-mocha and does not replicate the functionality. It does re-run the tests, but I think that is ok given how the coverage report is likely to be used relative to how the mocha test results are likely to be used.

Let me know if you think I can close this ticket.

**Comment by sindresorhus** [comment] 2014-01-10 08:21
Hmm, I'm not convinced, but I don't have a better suggestion either.

**Comment by dylanb** [comment] 2014-01-10 16:58
Well ideally, I'd like to be able to do the following with gulp:
1. Pre-process the test targets to add instrumentation
2. Run the tests
3. Process the results and produce a report

The gulp code would look like:

```
gulp.task('coveredtest', function () {
    gulp.src(['src.js'], { read: false })
        .pipe(instrument({
            ...options...
        }))
        .pipe(mocha({
            reporter: 'spec'
        }))
        .pipe(report({
            outputFile: 'coverage.html',
            reporter: 'html-cov'
        }));
});
```

This would make it independent of the test system altogether.

Thoughts?

**Comment by sindresorhus** [comment] 2014-01-10 17:10
I like it. Similar to: https://github.com/yeoman/generator/blob/master/gulpfile.js#L12-L19

**Comment by dylanb** [comment] 2014-01-15 00:06
ok, I had to basically refactor the entire coverage code and so I ended up implementing this in a different library. Can be seen here:

https://github.com/dylanb/gulp-coverage

Would like feedback on that there - is still a work in progress but I think the basic design works well.

**Comment by sindresorhus** [comment] 2014-01-17 22:10
Nice :)

I don't like `filePattern` and `ignoreFiles`. I would rather use one options called filter which supports globbing (globbing can be negated whichs moots ignoreFiles). Check out https://github.com/sindresorhus/multimatch

For `debugDirectory` i think it should just be a boolean, and if true you replace the original output files.

For the reporter, instead of `outFile` you should just be creating a new vinyl file and adding it to the stream. Docs https://github.com/gulpjs/gulp-util#new-fileobj

I would use through2 for a nicer interface to streams.

**Comment by dylanb** [comment] 2014-01-18 20:02
@sindresorhus if I create a new vinyl file and output it to the stream, how will downstream plugins know to differentiate these files from the original files?

Another question is right now, the reporter is called once for each file passed through the stream. There is no mechanism to process all of the report generation only once and only once all files have been processed upstream. Do you have any suggestions for best practices on solving this?

**Comment by yocontra** [comment] 2014-01-18 20:43
@dylanb They shouldn't need to. For buffering all files then doing something use through2 where your process fn pushes the file to an array and your end function is your plugin stuff on the array of files

**Comment by dylanb** [comment] 2014-01-19 02:42
@sindresorhus I was struggling with the flush method being called and finally figured out why it was no longer working. The problem is that all my tests rely on gulp-mocha and your latest rewrite of that makes it incompatible with Transform stream plugins

I have submitted a PR that fixes the problem https://github.com/sindresorhus/gulp-mocha/pull/14

**Comment by dylanb** [comment] 2014-02-09 23:36
Ok, I think I now have the gulp-coverage plugin where it needs to be. I would like your feedback on this as it is. I am now doing globbing and am passing the data through from the format task as a vinyl file. However, I did decide to no longer pass through the original files because I cannot find any standardized way of allowing downstream tasks to be able to differentiate between the original file and the file that I add for the coverage reports.

thoughts?

**Comment by sindresorhus** [comment] 2014-10-10 11:02
@dylanb I guess this can be closed?

**Closed as completed** 2014-10-12 16:21 UTC
